### ISSUE TITLE
CMake: get_filename_component called with incorrect number of arguments

### ISSUE THREAD

**Issue by dessertplanet** [4ms/looping-delay#1]
Hi there!

Working on getting this building so that I can customize my kit module. I'm using the 4ms-dev-env from here: https://github.com/4ms/4ms-dev-env and it doesn't seem to work? First CMake from the env has version < 15 and that causes the cmake -B build command to fail.

I tried building cmake 15.4 from source and after doing that I get a new set of errors (see below)

Any help would be greatly appreciated. Thank you for this awesome module and all that you do!

Cheers,
Dune

```
CMake Error at cmake/arm-none-eabi-gcc.cmake:19 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/CMakeDetermineSystem.cmake:93 (include)
  CMakeLists.txt:7 (project)


CMake Error at cmake/arm-none-eabi-gcc.cmake:19 (get_filename_component):
  get_filename_component called with incorrect number of arguments
Call Stack (most recent call first):
  build/CMakeFiles/3.15.4/CMakeSystem.cmake:6 (include)
  CMakeLists.txt:7 (project)


-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
-- The ASM compiler identification is unknown
-- Found assembler: arm-none-eabi-gcc
CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_C_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_CXX_COMPILER:

    arm-none-eabi-g++

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:7 (project):
  The CMAKE_ASM_COMPILER:

    arm-none-eabi-gcc

  is not a full path and was not found in the PATH.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Warning: Did not find file Compiler/-ASM
-- Configuring incomplete, errors occurred!
```

**Comment by dessertplanet** [comment]
Having successfully compiled DLD on MacOS, I am realizing that the dev-env isn't right for looping-delay. I am assuming I just need to get the right version of gcc-arm-none-eabi for this project

**Comment by danngreen** [comment]
Hi, Yes actually I haven't kept the 4ms-dev-env updated and maintained, so it's not worth using for this project. I should make a note in that project's README. 

Looking at the error log, it does just seem like you need to have arm-none-eabi-gcc on your PATH. Versions 12.2 and 12.3
are known to work.
I'll make a note in the README about needing that installed and on your PATH.

**Comment by dessertplanet** [comment]
Beautiful thank you! I now have it compiling on my macOS Apple Silicon host.

I was having issues with cmake latest from homebrew so I downgraded to 3.15.3 and had to comment out the definition and use of recover_from_task_fault() in the mdrivlib library because I was seeing this error:

```
Code/looping-delay/lib/mdrivlib/drivers/hal_handlers.cc.obj: in function `recover_from_task_fault()':
/Code/looping-delay/lib/CMSIS/Include/cmsis_gcc.h:879: multiple definition of `recover_from_task_fault()'; /Code/looping-delay/lib/CMSIS/Include/cmsis_gcc.h:879: first defined here
```

But with the older make and those quick changes this is resolved. Thank you for your help!
