### ISSUE TITLE
WebDFU download succeeds with 723-combo.hex but afterwards module is dark 

### ISSUE THREAD

**Issue by dessertplanet** [4ms/looping-delay#2]
No response from my looping-delay after successfully loading my locally built 723-combo.hex (I've uploaded it here: https://1drv.ms/u/s!AiRN-7GoMw3Z6A_Z-y7IbqlwkmyI?e=freoeK ). Any idea on how to troubleshoot?

This is a DIY kit that was working fine on the original firmware for sometime.

Only warnings on my "make combo" command now are:

```
warning: 723.elf has a LOAD segment with RWX permissions
warning: 723-bootloader.elf has a LOAD segment with RWX permissions
```

Thank you for your patience with this relative noob to hardware things-
And thank you for your hard work on these things! Love your modules.

**Comment by dessertplanet** [comment]
Here is the change I made to the lib to fix the compile error- I wonder if that could be tripping up something else in ld-kit land https://github.com/dessertplanet/mdrivlib/commit/bd158afaf0a62c7ccca73ce166464a0b080459e2

**Comment by dessertplanet** [comment]
Also screenshot of my DFU page in case I messed something up there:

![image](https://github.com/user-attachments/assets/f144765f-3d78-4af8-a77e-398433b4ec24)

**Comment by danngreen** [comment]
Just to check, you do have the v1.0 Brainboard, right? We just released a new Brainboard v1.1 that uses the F746 chip, and the boards need different firmwares.
I have it on my TODO to merge the F746 firmware branch into this repo,

**Comment by dessertplanet** [comment]
Yep "Kit Brainboard v1.0"

2 thoughts: 

1. Any chance you could provide a known good 723-combo.hex so I can test my upload system?
2. What version of ninja are you using? Looks like I have 1.12.1

**Comment by danngreen** [comment]
Aha! I see the problem. There's an error in the docs: it says to use USB-DFU to flash a .hex file, but it should be the .bin file! The hex file is not executable, so would only work with a programmer that can interpret it like a J-link or ST-link.

Also, the `make combo` target doesn't automatically generate the combo .bin file, so I'll fix that too.

BTW to answer your questions:

I'm using Ninja v1.12.1, and also have used it with v1.11.1, though I'd be surprised if it matters.

> ```
> warning: 723.elf has a LOAD segment with RWX permissions
> warning: 723-bootloader.elf has a LOAD segment with RWX permissions
> ```

These aren't important warnings, they aren't relevant to this project. 

The linker error that `recover_from_task_fault` is defined twice is something we fixed on our dev branch a while ago and I never backported that into the public branch. We fixed it by removing those functions from main.cc and bootloader/main.cc. Though, the way you changed it shouldn't cause a problem.

Also we have support for the new brainboard, so I'll merge all those changes in, too.

**Comment by dessertplanet** [comment]
Beautiful! All works now. I'm able to load 723-combo.bin no problem and all other errors disappear with the latest changes as well. 

Thank you so much for your help, @danngreen! Really appreciate the responsiveness and quick turnaround.

Cheers,
Dune

**Comment by danngreen** [comment]
Thanks for reporting the issues! It helps a lot
Also, in case anyone else wanders to this page, there are now Releases where you can download firmware binaries:
https://github.com/4ms/looping-delay/releases
